compressionLevel: mixed

enableScripts: false

# React Native / Expo require using typical node_modules installs
# i.e. incompatible with Yarn PnP (and Zero-Installs)
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
