/**
 * TODO: Migrate RN Storybook from 6.5.x to 10 (RN 0.71 to 0.83)
 */

import './doctools'
// storybook.requires.js auto generated by storybook
import './storybook.requires'

import { getStorybookUI } from '@storybook/react-native'
// import { SafeAreaView } from 'react-native'

// https://github.com/storybookjs/react-native#getstorybookui-options
const StorybookUIRoot = getStorybookUI({
  enableWebsockets: true // for @storybook/react-native-server
  // initialSelection: { kind: 'TextInput', name: 'Basic' },
  // shouldPersistSelection: false,
  // onDeviceUI: false
})

export default () => (
  // <SafeAreaView>
  <StorybookUIRoot />
  // </SafeAreaView>
)
